name: William Denton
description: Occasional Thoughts on Software, Hacking, IoT and Life

socialShareImage: /assets/images/defaultsocialshareimage.gif

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://william.denton.nz'
google_analytics: ''
azure_app_insights: 'bc180032-ea25-443d-8614-e0c7c2f23635'
disqus_shortname: 'williamdenton-blog'
twitter: 'wdento'
profile_image: '/assets/images/profile.jpg'

# Details for the RSS feed generator
url:            'http://william.denton.nz'
author:         'William Denton'
